# Generated by Django 3.1.2 on 2020-11-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiting', '0001_initial'),
        ('user', '0001_initial'),
        ('applying', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applying',
            name='recruiting_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.recruiting'),
        ),
        migrations.AddField(
            model_name='applying',
            name='user_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
