# Generated by Django 3.1.2 on 2020-11-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField()),
                ('user_id', models.CharField(max_length=20)),
                ('user_pw', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_name', models.CharField(max_length=20)),
                ('user_adress', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
