# Generated by Django 3.1.2 on 2020-11-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('borad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('borad_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borad.borad')),
                ('user_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
